apiVersion: v1
kind: Service
metadata:
  name: online-research-agent-backend-svc
  namespace: scb
spec:
  selector:
    app: online-research-agent
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
